# Entries with no nix-darwin homebrew-module equivalent.
# taps/brews/casks live in darwin/homebrew.nix and are applied by
# `nix run .#switch`. go/npm are not standard `brew bundle` directives
# and are kept commented out as an install memo; vscode extensions can be
# applied with `brew bundle --file=Brewfile`.
vscode "3w36zj6.textlint"
vscode "8amjp.charactercount"
vscode "ahmadalli.vscode-nginx-conf"
vscode "anthropic.claude-code"
vscode "bierner.markdown-mermaid"
vscode "biomejs.biome"
vscode "bmewburn.vscode-intelephense-client"
vscode "bradlc.vscode-tailwindcss"
vscode "castwide.solargraph"
vscode "cweijan.dbclient-jdbc"
vscode "cweijan.vscode-database-client2"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "editorconfig.editorconfig"
vscode "fallenmax.mithril-emmet"
vscode "foam.foam-vscode"
vscode "gera2ld.markmap-vscode"
vscode "github.vscode-github-actions"
vscode "goessner.mdmath"
vscode "golang.go"
vscode "hediet.vscode-drawio"
vscode "ipedrazas.kubernetes-snippets"
vscode "jakebathman.mysql-syntax"
vscode "jebbs.plantuml"
vscode "k--kato.docomment"
vscode "k--kato.intellij-idea-keybindings"
vscode "marp-team.marp-vscode"
vscode "mermaidchart.vscode-mermaid-chart"
vscode "mrcrowl.hg"
vscode "mrmlnc.vscode-apache"
vscode "ms-azuretools.vscode-containers"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.copilot-mermaid-diagram"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.mono-debug"
vscode "ms-vscode.vscode-speech"
vscode "ms-vscode.wordcount"
vscode "msysyamamoto.vscode-fluentd"
vscode "openai.chatgpt"
vscode "pkief.material-icon-theme"
vscode "raynigon.nginx-formatter"
vscode "redhat.vscode-yaml"
vscode "rooveterinaryinc.roo-cline"
vscode "rust-lang.rust-analyzer"
vscode "ryu1kn.annotator"
vscode "shanoor.vscode-nginx"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "shopify.ruby-lsp"
vscode "slevesque.shader"
vscode "styled-components.vscode-styled-components"
vscode "teabyii.ayu"
vscode "technosophos.vscode-helm"
vscode "techtrain.railway-vscode"
vscode "tekumara.typos-vscode"
vscode "toba.vsfire"
vscode "tomoki1207.pdf"
vscode "victoriadrake.kabukicho"
vscode "vscodevim.vim"
vscode "xyz.plsql-language"
vscode "zhuangtongfa.material-theme"
# go "github.com/GoogleCloudPlatform/cloudsql-proxy/cmd/cloud_sql_proxy"
# go "github.com/daixiang0/gci"
# go "github.com/ramya-rao-a/go-outline"
# go "github.com/stamblerre/gocode"
# go "github.com/rogpeppe/godef"
# go "golang.org/x/tools/cmd/goimports"
# go "github.com/fatih/gomodifytags"
# go "github.com/haya14busa/goplay/cmd/goplay"
# go "golang.org/x/tools/gopls"
# go "github.com/cweill/gotests/gotests"
# go "github.com/d-kuro/gwq/cmd/gwq"
# go "github.com/josharian/impl"
# go "github.com/mattn/memo"
# go "github.com/golang/mock/mockgen"
# go "go.ngrok.com/cmd/ngrok"
# go "github.com/google/skicka"
# go "github.com/cloudspannerecosystem/spanner-cli"
# go "honnef.co/go/tools/cmd/staticcheck"
# go "github.com/valbeat/whatday"
# npm "@openai/codex"
# npm "corepack"
